const arregloFrases = [
    "La tormenta no puede romper al árbol que sabe doblarse. Aprende a ser fuerte, no rígido.",
    "El pasado puede doler, pero es un maestro paciente. Pregunta, aprende y luego sigue adelante.",
    "El río no se pregunta a dónde va; simplemente fluye. Confía en el curso de la vida.",
    "La sombra no existe sin la luz. Tus miedos son solo la prueba de que puedes brillar.",
    "Quien camina lento, ve más detalles. No te apures en tu camino, saborea cada paso.",
    "El silencio no significa ausencia; a veces, es donde la sabiduría habla más fuerte.",
    "Una semilla en la oscuridad no duda; sabe que su tiempo para florecer llegará.",
    "Cuando el viento sopla fuerte, los cimientos bien plantados no tiemblan.",
    "La paciencia no es esperar sin hacer nada, es hacer todo con la certeza del momento correcto.",
    "El verdadero viaje no es hacia afuera, sino hacia adentro, donde reside tu esencia.",
    "Un corazón agradecido transforma el peso de las cargas en alas para volar.",
    "No es la cima lo que define tu grandeza, sino cómo enfrentas el ascenso.",
    "La luna no compite con el sol; ambos saben que su momento llegará.",
    "El conocimiento llena la mente; la sabiduría llena el alma.",
    "No temas las caídas; ellas enseñan cómo levantarte con más fuerza.",
    "El agua más pura fluye de las montañas más altas, después de enfrentar rocas y precipicios.",
    "Quien escucha más de lo que habla, aprende más de lo que imagina.",
    "La clave no está en cambiar el mundo, sino en cambiar cómo lo miras.",
    "Una pregunta bien formulada vale más que mil respuestas superficiales.",
    "El tiempo no cura, pero sí enseña cómo bailar con las cicatrices.",
    "La raíz profunda no teme la tempestad; la superficial, sí.",
    "El sol brilla cada día, aunque las nubes intenten ocultarlo.",
    "Un paso pequeño, pero firme, tiene más valor que un salto inseguro.",
    "La oscuridad no existe para asustarte, sino para que descubras tu luz.",
    "Lo que guardas en tu corazón será el peso o la ligereza de tu caminar.",
    "El que sabe esperar encuentra la fruta en su punto más dulce.",
    "No busques el control en todo; a veces, soltar es la verdadera victoria.",
    "El mar no se agota de olas, ni tú de oportunidades para comenzar de nuevo.",
    "El eco en la montaña te enseña: lo que das, siempre vuelve a ti.",
    "El verdadero valor no es no sentir miedo, sino avanzar a pesar de él.",
    "El puente más sólido se construye con verdad y empatía.",
    "La libertad no está en escapar, sino en enfrentarte a lo que temes.",
    "El árbol frondoso comenzó como una semilla que nadie veía.",
    "Cuando dejas de luchar contra la corriente, aprendes a navegar con ella.",
    "La belleza de una flor no se mide por cuánto dura, sino por cuán plena es en su momento.",
    "Un corazón en paz tiene más fuerza que un ejército en guerra.",
    "La montaña que hoy parece imposible mañana será solo un recuerdo de tu fuerza.",
    "El reflejo en el agua solo se aclara cuando el agua está en calma.",
    "La riqueza del alma no se mide en monedas, sino en actos de bondad.",
    "El pájaro no teme a la rama que se rompe, porque confía en sus alas.",
    "La humildad no es pensar menos de ti mismo, sino pensar menos en ti mismo.",
    "La verdadera paz no es la ausencia de ruido, sino la calma en el corazón.",
    "La semilla que no teme al invierno florece más fuerte en primavera.",
    "Quien se conoce a sí mismo, conoce el universo entero.",
    "Las respuestas que buscas están en el silencio que temes escuchar.",
    "El amor no posee; libera.",
    "El que siembra con cuidado cosecha con alegría.",
    "El verdadero maestro no te da respuestas, sino que despierta tus preguntas.",
    "Cada día trae consigo la oportunidad de ser mejor que ayer.",
    "No sigas la multitud; el sendero más valioso suele ser el menos transitado.",
    "La clave para avanzar no es correr más rápido, sino detenerse a reflexionar." ,
    "El desierto no es vacío, solo está lleno de secretos que esperan ser descubiertos.",
    "El fuego más intenso puede encenderse con una chispa pequeña.",
    "El destino no está escrito, se crea paso a paso con tus elecciones.",
    "El respeto no se exige, se gana con actos de nobleza.",
    "La gratitud convierte lo que tienes en suficiente y más.",
    "No temas al cambio; a menudo es el camino hacia lo mejor de ti.",
    "Los caminos más difíciles llevan a los destinos más hermosos.",
    "Un amigo sincero es el espejo que refleja tu mejor versión.",
    "El amor verdadero no se encuentra, se construye cada día.",
    "La confianza en uno mismo es el puente hacia los sueños más grandes.",
    "La perseverancia transforma lo imposible en inevitable.",
    "La felicidad no es un lugar, es el camino que eliges recorrer.",
    "El conocimiento sin acción es como una semilla sin agua: no crece.",
    "El arco iris aparece después de la tormenta, no antes.",
    "La valentía no es la ausencia de miedo, es actuar a pesar de él.",
    "Los errores son los ladrillos del aprendizaje, no los muros de tu progreso.",
    "La verdadera riqueza es el tiempo que compartes con quienes amas.",
    "El mejor maestro no enseña, inspira.",
    "El amanecer siempre llega, incluso tras la noche más oscura.",
    "La naturaleza no apresura nada, pero todo se logra a su tiempo.",
    "Las palabras pueden construir puentes o derribar murallas: elige bien.",
    "El horizonte siempre está allí, recordándote que hay más por descubrir.",
    "La bondad no cuesta nada, pero su valor es incalculable.",
    "Quien vive con propósito no teme perderse, porque sabe hacia dónde va.",
    "El río no pelea con las rocas; simplemente las rodea y sigue su camino.",
    "La belleza no está en los ojos que miran, sino en el alma que percibe.",
    "El amor es la única fuerza que se multiplica cuando se comparte.",
    "La duda puede ser el inicio de la sabiduría, si aprendes a escucharla.",
    "El perdón no libera al otro, te libera a ti mismo.",
    "El árbol más alto empezó como una semilla bajo tierra.",
    "La risa es el lenguaje universal del alma.",
    "La curiosidad es la chispa que enciende el fuego del conocimiento.",
    "El mayor viaje comienza con un paso y una intención clara.",
    "La esperanza es el faro que guía al navegante en la tormenta.",
    "Quien abraza el presente, vive sin cadenas del pasado.",
    "La paciencia es la compañera del éxito duradero.",
    "El agradecimiento transforma lo ordinario en extraordinario.",
    "La vida no se mide en años, sino en momentos que quitan el aliento.",
    "El mayor regalo que puedes dar es tu atención sincera.",
    "El alma crece cuando enfrenta sus sombras con valentía.",
    "La sabiduría no está en saberlo todo, sino en saber aprender siempre.",
    "Los sueños grandes requieren corazones valientes." ,
    "El camino más largo comienza con un corazón decidido.",
    "La fuerza no viene de ganar, sino de levantarte cada vez que caes.",
    "Un río tranquilo refleja el cielo con mayor claridad.",
    "La simplicidad es la máxima expresión de la sabiduría.",
    "El cambio no siempre es fácil, pero siempre trae crecimiento.",
    "El amor no necesita ser perfecto, solo verdadero.",
    "La vida no se mide en éxitos, sino en momentos que tocan el alma.",
    "La resiliencia es el arte de transformar heridas en fortaleza.",
    "El valor se encuentra en los pequeños actos de bondad diaria.",
    "El presente es el único momento que realmente posees.",
    "El conocimiento puede abrir puertas, pero el carácter las mantiene abiertas.",
    "La serenidad viene de aceptar lo que no puedes cambiar y trabajar en lo que sí puedes.",
    "El árbol más frondoso una vez fue una pequeña semilla.",
    "El tiempo no espera a nadie, pero siempre da oportunidades a quien las busca.",
    "La belleza de la vida radica en su imperfección.",
    "Un corazón agradecido transforma los desafíos en aprendizajes.",
    "La humildad es la base de la verdadera grandeza.",
    "La verdadera riqueza está en lo que compartes, no en lo que acumulas.",
    "Un espíritu libre no teme a los cambios, los abraza.",
    "El silencio es la voz del alma cuando el mundo se vuelve demasiado ruidoso.",
    "La luz interior siempre encuentra una grieta para brillar.",
    "El perdón es el regalo que te liberas a ti mismo.",
    "El que busca la verdad debe estar dispuesto a cambiar.",
    "El éxito no se mide en logros, sino en la paz que encuentras en el proceso.",
    "La vida no se trata de esperar a que pase la tormenta, sino de aprender a bailar bajo la lluvia.",
    "La curiosidad es el motor del aprendizaje eterno.",
    "El amor propio es el cimiento de todas las relaciones sanas.",
    "El verdadero hogar está donde tu corazón se siente en paz.",
    "El camino de la sabiduría comienza con una simple pregunta.",
    "La paciencia no es simplemente esperar, es cómo te comportas mientras esperas.",
    "La alegría se encuentra en las pequeñas cosas que el alma agradece.",
    "El pasado es un espejo para aprender, no para vivir en él.",
    "La naturaleza no se apresura, pero todo lo logra.",
    "La compasión es el lenguaje universal de los corazones.",
    "Cada día es una página en blanco esperando ser escrita.",
    "La fortaleza reside en aceptar lo que eres y trabajar en lo que quieres ser.",
    "La verdadera conexión no necesita palabras, solo presencia.",
    "El viaje más importante es hacia tu interior.",
    "El tiempo es el recurso más valioso; úsalo sabiamente.",
    "La gratitud convierte lo que tienes en suficiente.",
    "El amor es el único tesoro que se multiplica al compartirlo.",
    "El equilibrio no es mantener todo en su lugar, sino saber qué soltar y qué sostener.",
    "La esperanza es el faro que guía al navegante en aguas turbulentas.",
    "La felicidad no es un destino, sino una forma de caminar.",
    "El respeto comienza por uno mismo.",
    "La armonía es el arte de bailar al ritmo del universo.",
    "La confianza es el puente entre el miedo y el valor.",
    "El cambio siempre trae consigo una lección oculta.",
    "El conocimiento crece cuando se comparte, no cuando se guarda.",
    "El coraje no es la ausencia de miedo, sino la decisión de seguir adelante a pesar de él.",
    "El mayor regalo que puedes dar es tu tiempo y atención.",
    "El aprendizaje nunca termina; cada día trae una nueva lección.",
    "La bondad genuina deja huellas que nunca se borran.",
    "La paz interior es la mejor armadura contra las tormentas externas.",
    "El éxito no se mide en riquezas, sino en la cantidad de vidas que tocas.",
    "El amor es la semilla de todas las cosas buenas.",
    "La perseverancia es el puente entre el esfuerzo y el logro.",
    "La verdad siempre encuentra su camino, aunque sea a través del silencio.",
    "La vida es un reflejo de las historias que cuentas sobre ella.",
    "El que siembra con esfuerzo cosecha con satisfacción.",
    "El alma en paz atrae todo lo que necesita.",
    "El universo conspira a favor de los que siguen su corazón.",
    "El tiempo cura, pero también enseña.",
    "La humildad es el suelo donde florece la sabiduría.",
    "El amor propio es el inicio de cualquier historia de éxito.",
    "El esfuerzo constante convierte lo ordinario en extraordinario.",
    "El propósito de la vida no es ser perfecto, sino auténtico.",
    "La intuición es la brújula que te guía hacia tu verdad.",
    "El pasado ya no tiene poder; el futuro es una promesa, pero el presente es un regalo.",
    "La fe no hace las cosas fáciles, pero las hace posibles.",
    "El mayor logro es ser fiel a uno mismo.",
    "La creatividad es el lenguaje del alma.",
    "El que no teme perder, ya ha ganado.",
    "La vida es más rica cuando compartes tus bendiciones.",
    "La luz no discute con la oscuridad; simplemente brilla.",
    "El destino no está escrito, se dibuja con cada elección.",
    "El amor no busca poseer, sino liberar.",
    "El carácter se forja en los momentos más difíciles.",
    "La aceptación de uno mismo es el inicio de toda transformación.",
    "El alma florece cuando encuentra su propósito.",
    "El mundo cambia cuando cambias tu forma de mirarlo.",
    "La confianza es el suelo fértil donde crece la relación.",
    "El mayor riesgo es no arriesgarse.",
    "La sabiduría no está en tener respuestas, sino en formular preguntas profundas.",
    "La libertad verdadera comienza cuando sueltas lo que no puedes controlar.",
    "El amor nunca se agota; cuanto más das, más tienes.",
    "El arte de la vida es aprender a dejar ir y a seguir adelante.",
    "La grandeza está en los pequeños actos hechos con amor.",
    "El universo entero cabe en un momento de plena conciencia.",
    "El mayor regalo que puedes dar al mundo es tu mejor versión.",  
    "La calma no se encuentra en el silencio exterior, sino en la serenidad interior.",
    "La luna nunca se preocupa por las nubes; sigue brillando en su momento.",
    "La verdadera fuerza radica en la habilidad de ser gentil.",
    "El aprendizaje más profundo viene de los errores más grandes.",
    "El agua nunca lucha contra el obstáculo, simplemente lo rodea.",
    "La gratitud es el arte de ver lo extraordinario en lo ordinario.",
    "El tiempo no espera a nadie, pero siempre deja lecciones.",
    "El valor de una persona no se mide por lo que posee, sino por lo que comparte.",
    "El viento no tiene forma, pero puede moldear montañas.",
    "Un corazón libre no teme a la incertidumbre, la abraza.",
    "La vida es un constante flujo; resistirse solo trae sufrimiento.",
    "La sombra de un árbol es tanto su refugio como su testimonio de crecimiento.",
    "El conocimiento es vasto, pero la sabiduría sabe qué aplicar.",
    "La paciencia es el camino más corto hacia el éxito verdadero.",
    "Una sonrisa sincera puede iluminar un día oscuro.",
    "El propósito de la vida no es llegar primero, sino disfrutar el viaje.",
    "La autenticidad es el lenguaje que el alma entiende.",
    "La confianza es el puente invisible que conecta corazones.",
    "El fuego necesita oxígeno, igual que los sueños necesitan acción.",
    "La verdadera riqueza está en la experiencia, no en las posesiones.",
    "La libertad se encuentra en soltar lo que no puedes controlar.",
    "La oscuridad no puede extinguir la llama de la esperanza.",
    "La semilla más pequeña puede dar el árbol más grande.",
    "El amor propio es el faro que guía en la tormenta.",
    "El alma que escucha aprende más que la boca que habla.",
    "La mayor batalla es la que peleas contigo mismo y tus miedos.",
    "Un paso valiente en la dirección correcta vale más que una carrera en círculos.",
    "El océano no se llena con una sola gota, pero cada gota cuenta.",
    "El amanecer siempre sigue a la noche más oscura.",
    "El respeto es la semilla de todas las relaciones duraderas.",
    "El silencio es el lenguaje que une a los corazones sabios.",
    "La gratitud convierte lo suficiente en abundancia.",
    "La flor más bella florece en el terreno más difícil.",
    "La mente abierta es un campo fértil para nuevas ideas.",
    "El tiempo bien usado se convierte en recuerdos valiosos.",
    "El coraje no elimina el miedo, lo transforma en fuerza.",
    "Cada cicatriz cuenta la historia de una batalla superada.",
    "La belleza verdadera no necesita adornos; brilla por sí sola.",
    "El éxito es el resultado de pequeños esfuerzos repetidos cada día.",
    "El amor no demanda, simplemente da.",
    "La paz no es la ausencia de problemas, sino la presencia de soluciones.",
    "El mayor regalo es tu tiempo, porque nunca puedes recuperarlo.",
    "La introspección es el primer paso hacia la sabiduría.",
    "El río no teme cambiar su curso para encontrar el mar.",
    "El crecimiento siempre implica dejar algo atrás.",
    "La intuición es la brújula del alma.",
    "La esperanza es el hilo dorado que conecta los sueños con la realidad.",
    "El perdón libera más al que lo da que al que lo recibe.",
    "La mente es un jardín; cuida las semillas que plantas.",
    "El mayor poder está en la capacidad de elegir tu respuesta.",
    "La naturaleza no compite, simplemente florece.",
    "La confianza se construye con actos, no con palabras.",
    "La paciencia es la fortaleza de los sabios.",
    "El amor es la fuerza que mueve el universo.",
    "La vida se expande o se contrae en proporción a tu valentía.",
    "El destino es un lienzo en blanco, y tú eres el artista.",
    "La bondad es el idioma que todos entienden.",
    "El respeto comienza cuando reconoces la dignidad en el otro.",
    "El tiempo no borra, pero suaviza las cicatrices.",
    "La luz interior nunca se apaga, solo espera ser descubierta.",
    "El éxito es la suma de decisiones sabias hechas con constancia.",
    "La mayor riqueza es estar en paz contigo mismo.",
    "El amor nunca es posesivo; su esencia es la libertad.",
    "La curiosidad abre puertas que el miedo mantiene cerradas.",
    "El equilibrio se encuentra en el punto medio entre el esfuerzo y la aceptación.",
    "La simplicidad es el último grado de sofisticación.",
    "La vida no es un problema a resolver, sino una experiencia a vivir.",
    "El río más profundo fluye con calma.",
    "La paciencia es el arte de mantener la calma mientras esperas.",
    "La mayor fuerza proviene del interior, no del exterior.",
    "El amor auténtico no necesita ser entendido, solo sentido.",
    "El camino correcto no siempre es el más fácil, pero sí el más gratificante.",
    "El perdón no cambia el pasado, pero transforma el futuro.",
    "La gratitud es la memoria del corazón.",
    "La creatividad es la expresión más pura del alma.",
    "La perseverancia convierte los sueños en realidad.",
    "La verdadera fortaleza no está en no caer, sino en levantarte cada vez.",
    "El amor no necesita razón, solo presencia.",
    "El conocimiento abre puertas, pero la sabiduría te guía a través de ellas.",
    "El tiempo bien usado es el mayor regalo que puedes darte a ti mismo.",
    "La aceptación es el primer paso hacia la libertad interior.",
    "El amor propio es el inicio de toda transformación positiva.",
    "El cambio siempre comienza desde adentro.",
    "La felicidad no es un destino, es una elección diaria.",
    "El respeto es el suelo fértil donde crecen las mejores relaciones.",
    "El alma valiente siempre encuentra un camino.", 
    "La semilla que plantas hoy será el fruto que coseches mañana.",
    "El viento no siempre sopla a favor, pero siempre impulsa a moverse.",
    "La paciencia es el suelo donde crece el éxito duradero.",
    "Un corazón en paz es más fuerte que cualquier tormenta externa.",
    "La grandeza no está en lo que logras, sino en cómo inspiras a otros.",
    "El verdadero poder no se muestra, se siente.",
    "La conexión más profunda es la que no necesita palabras.",
    "El conocimiento te da alas, pero la sabiduría te enseña a volar.",
    "La sombra siempre sigue al que camina bajo el sol.",
    "El amor propio es el cimiento de cualquier relación duradera.",
    "La humildad no disminuye tu valor; lo engrandece.",
    "Cada amanecer trae consigo una nueva oportunidad para crecer.",
    "La fe es el puente entre lo que es y lo que puede ser.",
    "El silencio es el refugio del alma cansada.",
    "La vida no siempre es justa, pero siempre es un regalo.",
    "La fortaleza se mide en la capacidad de seguir adelante, no en la ausencia de debilidad.",
    "El tiempo no tiene prisa, pero nunca se detiene.",
    "La verdadera libertad comienza en la mente.",
    "El mayor tesoro que posees es el presente.",
    "El respeto hacia los demás refleja el respeto hacia uno mismo.",
    "La confianza se construye con actos, no con palabras.",
    "El arte de vivir está en encontrar belleza incluso en la adversidad.",
    "El perdón es el regalo más grande que puedes darte a ti mismo.",
    "El camino a la sabiduría comienza con la aceptación del cambio.",
    "La bondad no necesita un motivo, es suficiente ser.",
    "El equilibrio se encuentra en saber cuándo avanzar y cuándo detenerse.",
    "La gratitud transforma los días comunes en bendiciones.",
    "El valor no es la ausencia de miedo, sino actuar a pesar de él.",
    "La naturaleza no se apresura, pero todo lo logra.",
    "El amor no busca ser perfecto, solo sincero.",
    "El tiempo es un maestro paciente y un juez implacable.",
    "La verdadera riqueza está en las experiencias que coleccionas.",
    "El alma que sueña nunca envejece.",
    "La fortaleza se construye en los momentos de mayor desafío.",
    "El camino correcto no siempre es el más fácil.",
    "El conocimiento puede llenar tu mente, pero la sabiduría llena tu vida.",
    "El horizonte siempre está ahí, esperando a ser alcanzado.",
    "El amor es el lenguaje universal del corazón.",
    "La perseverancia transforma la esperanza en realidad.",
    "El éxito es el resultado de decisiones pequeñas hechas bien todos los días.",
    "La paz interior es el mayor logro que puedes alcanzar.",
    "El alma que escucha encuentra respuestas en el silencio.",
    "El futuro no está escrito, pero las acciones de hoy lo moldean.",
    "El respeto por la vida comienza con el respeto por uno mismo.",
    "El río no lucha contra las rocas; las rodea.",
    "La creatividad es el susurro del alma.",
    "La paciencia abre puertas que la prisa deja cerradas.",
    "La fe es la chispa que enciende los sueños.",
    "El amor es el único tesoro que crece cuando se comparte.",
    "La sabiduría no consiste en saber mucho, sino en aplicar lo que sabes.",
    "La verdadera belleza está en los ojos que saben mirar más allá.",
    "El corazón que ama es siempre joven.",
    "La felicidad no es un destino, es la forma en que viajas.",
    "El verdadero coraje es ser tú mismo en un mundo que intenta cambiarte.",
    "La gratitud convierte lo que tienes en suficiente.",
    "El perdón es la llave que libera al alma del resentimiento.",
    "El universo habla en susurros; aprende a escuchar.",
    "El amor nunca exige, solo da.",
    "La humildad es el suelo fértil donde crece la sabiduría.",
    "La esperanza es la luz que guía incluso en la noche más oscura.",
    "El verdadero éxito es vivir en armonía contigo mismo.",
    "La paciencia es el arte de esperar con una actitud positiva.",
    "El río más profundo fluye en calma.",
    "La conexión más valiosa es la que haces contigo mismo.",
    "El mayor regalo que puedes dar es tu tiempo y atención.",
    "El cambio siempre trae consigo una oportunidad de crecimiento.",
    "El alma valiente siempre encuentra un camino.",
    "El silencio es el refugio donde el alma se encuentra consigo misma.",
    "La verdadera fuerza radica en la bondad.",
    "El amor es el hilo dorado que teje la vida.",
    "El mayor acto de valentía es ser tú mismo.",
    "El tiempo nunca se detiene, pero siempre enseña.",
    "El conocimiento te lleva lejos; la sabiduría te lleva profundo.",
    "El amor propio es el inicio de todas las historias hermosas.",
    "La gratitud es la memoria del corazón.",
    "La libertad comienza cuando dejas de buscar la aprobación de otros.",
    "El respeto es el puente que une a las almas.",
    "El verdadero viaje es hacia tu interior.",
    "El aprendizaje nunca termina; cada día es una lección.",
    "El equilibrio no es mantener todo igual, sino adaptarte al cambio.",
    "El amor siempre encuentra un camino, incluso en los lugares más oscuros.",
    "La serenidad es el regalo de la aceptación.",
    "El alma que busca siempre encuentra.",
    "Cada paso que das en la oscuridad te acerca a la luz.",
    "La sabiduría no grita, susurra al corazón atento.",
    "El alma tranquila es el mayor refugio contra el caos.",
    "Los pequeños actos de bondad tienen un gran impacto.",
    "El éxito sin propósito es como un río sin dirección.",
    "La aceptación no es rendición, es libertad.",
    "El valor es seguir adelante cuando todo parece perdido.",
    "La verdadera grandeza radica en servir a los demás.",
    "El silencio tiene más respuestas que mil palabras.",
    "La gratitud es el lenguaje universal de la felicidad.",
    "Cada día es una nueva oportunidad para reinventarte.",
    "La conexión con la naturaleza sana el alma.",
    "El tiempo es un maestro que no perdona distracciones.",
    "La confianza en uno mismo abre puertas invisibles.",
    "El amor propio es la raíz de todas las relaciones saludables.",
    "El pasado enseña, pero no define tu presente.",
    "La serenidad es el arte de mantener la calma bajo presión.",
    "Un corazón abierto es un puente hacia nuevas posibilidades.",
    "La vida no espera; abraza el momento ahora.",
    "La luz interior nunca se apaga, solo necesita ser avivada.",
    "El conocimiento se acumula, pero la sabiduría fluye.",
    "La paciencia no es pasiva; es fuerza en reposo.",
    "El cambio es el único constante; aprende a fluir con él.",
    "La verdadera libertad es ser fiel a quien eres.",
    "El valor de un sueño se mide por el esfuerzo que le dedicas.",
    "La esperanza es un faro en los días nublados.",
    "La introspección es la llave de la transformación personal.",
    "El río no teme al obstáculo, lo convierte en parte de su camino.",
    "El amor es un jardín que florece con cuidado y tiempo.",
    "El equilibrio entre mente y corazón crea armonía.",
    "El perdón es una medicina que cura al que lo da.",
    "La sencillez es la máxima expresión de la sabiduría.",
    "El momento más oscuro es justo antes del amanecer.",
    "La persistencia convierte lo imposible en inevitable.",
    "El respeto hacia los demás es un reflejo de tu carácter.",
    "La curiosidad es la chispa que enciende el aprendizaje.",
    "El amor auténtico no busca poseer, sino liberar.",
    "El universo se alinea con quienes persiguen su propósito.",
    "La empatía construye puentes que las palabras no pueden.",
    "La gratitud convierte los retos en regalos.",
    "La disciplina es la hermana del éxito.",
    "La humildad abre puertas que el orgullo cierra.",
    "El alma en paz escucha mejor al universo.",
    "El esfuerzo constante supera al talento sin dirección.",
    "El valor no elimina el miedo, lo transforma en acción.",
    "La bondad es el eco del corazón más puro.",
    "El conocimiento es poder; la sabiduría es libertad.",
    "La vida es un espejo: refleja lo que proyectas.",
    "El amor es el único camino hacia la eternidad.",
    "Esta es la ultima frase, ya no hay más"
];

export default arregloFrases;