const arregloFrases = [
    "No todas las raíces se ven, pero son las que sostienen lo más grande de ti.",
    "Hay fuerza en quien se atreve a empezar de nuevo, incluso con las manos vacías.",
    "Cada amanecer es una segunda oportunidad que no pide explicaciones.",
    "No necesitas tenerlo todo claro para dar el primer paso, solo confianza.",
    "El sol no deja de salir por una noche oscura; tampoco tú por un mal día.",
    "Cuando el alma se cansa, el cuerpo lo grita. Escúchate, respeta tus pausas.",
    "Las flores más resistentes son las que crecieron entre piedras.",
    "La claridad no siempre llega en medio del ruido, sino cuando te atreves a detenerte.",
    "No siempre se trata de avanzar, a veces se trata de no rendirse.",
    "Perderse no es fracasar; es explorar caminos que aún no sabías que existían.",
    "El miedo no desaparece, pero tú puedes aprender a caminar con él.",
    "A veces lo que más pesa no son las cargas, sino lo que no te permites soltar.",
    "Cada cicatriz cuenta una historia de algo que superaste. No las ocultes.",
    "Si el camino se ve difícil, tal vez es porque estás construyendo uno nuevo.",
    "El valor no es la ausencia de duda, es seguir a pesar de ella.",
    "Recuerda: hasta el invierno más crudo prepara el terreno para la primavera.",
    "No compares tu capítulo uno con el capítulo veinte de alguien más.",
    "Lo que hoy parece un muro, mañana será parte del paisaje que superaste.",
    "No necesitas validación externa para tener valor interno.",
    "No eres débil por caer, eres fuerte por levantarte sin que nadie lo vea.",
    "La fe no siempre grita, a veces es un susurro que dice: 'intenta una vez más'.",
    "Hay caminos que solo se abren cuando confías lo suficiente para caminar sin ver.",
    "No estás retrocediendo, estás tomando impulso.",
    "Hasta las hojas secas tienen su función: alimentar nuevas raíces.",
    "Siembra intención, riega con acción y confía en el tiempo.",
    "La grandeza no siempre hace ruido; a veces crece en silencio.",
    "A veces no se trata de tener más fuerza, sino más sentido.",
    "Recuerda que sobreviviste a días que pensaste que no podrías.",
  
    // Frases estilo más motivacional, directo
    "Hazlo cansado, hazlo con miedo, pero hazlo.",
    "No esperes a tener energía para moverte; muévete y la energía llegará.",
    "No eres tu peor día, eres todo lo que haces para seguir adelante.",
    "La disciplina te lleva donde la motivación no alcanza.",
    "Tu versión futura te está esperando. No la hagas esperar más.",
    "No se trata de tener suerte, se trata de no rendirse.",
    "Pequeños pasos diarios crean cambios gigantes.",
    "Cada día que no te rindes, ya estás ganando.",
    "Tú no tienes límites, solo decisiones pendientes.",
    "Cuando no sabes qué hacer, haz lo que sabes: sigue.",
    "Hazlo por ti. Por quien fuiste, por quien eres y por quien vas a ser.",
    "El momento perfecto no existe, pero tú sí estás listo.",
    "Sé constante. Lo extraordinario es solo lo ordinario repetido con fe.",
    "No dejes que la duda ocupe el lugar de tus ganas.",
    "Si te cansas, aprende a descansar, no a rendirte.",
    "Tú no empezaste para quedarte a medias.",
    "Todo cambia cuando decides que ya no te vas a traicionar.",
    "No tienes que hacerlo todo hoy. Solo no dejes de hacerlo.",
    "Hoy es el mejor día para no rendirte.",
    "No necesitas sentirte capaz para actuar, necesitas actuar para sentirte capaz."
  ];
  

export default arregloFrases;