const arregloFrases = [
"Cada día es una página en blanco para escribir una historia de éxito",  
"La gratitud es la semilla que hace florecer la felicidad",  
"Los sueños grandes requieren esfuerzo constante y determinación",  
"El cambio comienza cuando decides salir de tu zona de confort",  
"La confianza en ti mismo es la clave para abrir todas las puertas",  
"Recuerda que el fracaso es solo una lección disfrazada",  
"El presente es el mejor momento para tomar acción",  
"Tu fuerza interior es más grande de lo que imaginas",  
"La vida siempre recompensa a quienes actúan con propósito",  
"No dejes que las dudas apaguen tu luz, sigue brillando",  
"Cada paso, por pequeño que sea, te lleva más cerca de tus metas",  
"Los pensamientos positivos crean vidas positivas",  
"Confía en el proceso, incluso cuando los resultados tarden en llegar",  
"Tu persistencia puede mover montañas",  
"La autenticidad es tu superpoder, nunca lo subestimes",  
"Agradece por cada lección, incluso las más difíciles",  
"Rodéate de personas que te eleven y te inspiren",  
"Cada día es una nueva oportunidad para comenzar de nuevo",  
"La paz comienza cuando aceptas las cosas que no puedes cambiar",  
"Recuerda que el éxito es un viaje, no un destino",  
"El cambio más pequeño puede tener el impacto más grande",  
"La creatividad nace cuando permites que tu mente sueñe",  
"Hoy es un buen día para liberar lo que ya no necesitas",  
"El amor propio es la base de todas tus relaciones",  
"Todo lo que necesitas para avanzar ya está dentro de ti",  
"Los momentos de calma son los que más claridad traen",  
"Confía en que estás exactamente donde necesitas estar",  
"La paciencia es la clave para cosechar grandes resultados",  
"La bondad hacia los demás empieza por la bondad hacia ti mismo",  
"Cada amanecer es una nueva oportunidad para dar lo mejor de ti",  
"El éxito está en tu capacidad de no rendirte jamás",  
"Permítete soñar en grande y dar pequeños pasos hacia ello",  
"Tu historia tiene el poder de inspirar a quienes te rodean",  
"La valentía es actuar incluso cuando sientes miedo",  
"Recuerda que eres más fuerte que cualquier obstáculo",  
"El agradecimiento transforma lo ordinario en extraordinario",  
"El presente es un regalo, ábrelo con gratitud y entusiasmo",  
"Confía en el tiempo y en el ritmo natural de la vida",  
"El mejor momento para empezar es ahora",  
"Abraza cada desafío como una oportunidad para crecer",  
"La acción es la clave para convertir sueños en realidad",  
"Tu paz interior es tu mayor fortaleza, cuídala",  
"El éxito empieza cuando dejas de buscar excusas",  
"Cada decisión que tomas moldea tu destino",  
"La constancia es el puente entre tus sueños y tus logros",  
"La felicidad está en las pequeñas cosas que haces con amor",  
"Deja ir lo que no puedes controlar y abraza el presente",  
"La pasión por lo que haces marca la diferencia",  
"Cada día es un nuevo comienzo, aprovecha cada momento",  
"La gratitud te conecta con la abundancia de la vida",  
"Recuerda que tus pensamientos crean tu realidad",  
"El éxito está reservado para quienes nunca dejan de intentarlo",  
"El esfuerzo que haces hoy es la recompensa de mañana",  
"La confianza en ti mismo es tu mayor aliado",  
"Cada paso hacia adelante, por pequeño que sea, cuenta",  
"La vida te enseña algo nuevo cada día, presta atención",  
"El cambio más grande comienza con una pequeña acción",  
"La felicidad se encuentra cuando te permites ser tú mismo",  
"Recuerda que todo lo que necesitas está dentro de ti",  
"La gratitud es el imán que atrae más razones para ser feliz",  
"Tu energía y enfoque son los ingredientes de tus logros",  
"Confía en el proceso y disfruta el camino hacia tus metas",  
"El presente es el mejor momento para tomar decisiones valientes",  
"La perseverancia y el compromiso siempre rinden frutos",  
"La felicidad es el resultado de vivir con propósito",  
"El esfuerzo constante crea resultados extraordinarios",  
"Rodéate de personas que te inspiren a crecer",  
"Recuerda que las pequeñas acciones generan grandes cambios",  
"El amor propio es la base de una vida plena y feliz",  
"Confía en que cada día te acerca más a tus sueños",  
"El éxito es el resultado de la disciplina y la constancia",  
"Tu camino es único, recórrelo con confianza y determinación",  
"La gratitud es el puente hacia una vida más abundante",  
"Recuerda que cada momento tiene su propósito, acéptalo",  
"La calma y el enfoque te llevarán más lejos de lo que imaginas",  
"Cada desafío que enfrentas te hace más fuerte y sabio",  
"Confía en el ritmo natural de la vida, todo llega a su tiempo",
"El éxito no se mide por lo que logras, sino por los obstáculos que superas",  
"La verdadera riqueza está en vivir con gratitud y propósito",  
"La paciencia es la clave para alcanzar grandes metas",  
"Cada amanecer es una nueva oportunidad para ser tu mejor versión",  
"La felicidad se encuentra en disfrutar el proceso, no solo el resultado",  
"Los errores son lecciones disfrazadas, aprende de ellos",  
"El esfuerzo constante crea los cimientos del éxito",  
"Tu actitud determina cómo enfrentas cada desafío",  
"El amor propio es el primer paso hacia una vida plena",  
"Confía en que todo ocurre por una razón y en el momento indicado",  
"Las acciones pequeñas, realizadas con constancia, generan grandes cambios",  
"La gratitud transforma lo ordinario en extraordinario",  
"El cambio que deseas empieza con una decisión valiente",  
"Recuerda que cada día es una página en blanco para escribir tu historia",  
"La calma interior es la base para tomar decisiones acertadas",  
"El presente es el único momento que realmente tienes, vívelo plenamente",  
"Tu potencial es ilimitado, no te pongas barreras",  
"La perseverancia siempre supera al talento sin esfuerzo",  
"La confianza en ti mismo abre puertas que antes parecían cerradas",  
"Cada paso que das, por pequeño que sea, te acerca a tus sueños",  
"La gratitud es el imán que atrae más cosas buenas a tu vida",  
"Los pensamientos positivos tienen el poder de transformar tu realidad",  
"El éxito llega a quienes trabajan con pasión y compromiso",  
"Recuerda que eres más fuerte de lo que crees",  
"La felicidad no es el destino, sino el camino que recorres",  
"Abraza los retos, ellos te ayudarán a crecer",  
"Tu historia tiene valor, inspírate y comparte lo que has aprendido",  
"Rodéate de energía positiva y deja ir lo que ya no suma",  
"El amor por lo que haces es lo que marca la diferencia",  
"Hoy es el día perfecto para dar el primer paso hacia tus metas",  
"La acción vence al miedo, hazlo incluso si dudas",  
"Tu fortaleza se construye en los días difíciles, no te detengas",  
"La gratitud es la llave que abre las puertas a la abundancia",  
"La confianza en el proceso es clave para mantener la calma",  
"Cada día trae consigo nuevas oportunidades, aprovéchalas",  
"El cambio comienza en el momento en que decides intentarlo",  
"Tu energía es tu mayor recurso, úsala sabiamente",  
"El éxito no es algo que encuentras, es algo que construyes",  
"Las decisiones valientes siempre tienen recompensas inesperadas",  
"Tu mejor versión está esperando a que des el primer paso",  
"Los pequeños avances diarios conducen a grandes logros",  
"El tiempo que dedicas a ti mismo nunca es tiempo perdido",  
"Confía en que cada paso que das te lleva en la dirección correcta",  
"Rodéate de personas que celebren tus éxitos y te impulsen a crecer",  
"El cambio más pequeño puede tener el impacto más grande",  
"Las metas grandes se alcanzan con pequeños pasos constantes",  
"La gratitud es el lenguaje del corazón",  
"Confía en que lo que estás haciendo tiene un propósito mayor",  
"El amor propio es la base para construir relaciones saludables",  
"Cada día es una nueva oportunidad para aprender algo nuevo",  
"Tu historia tiene el poder de inspirar a otros, no dejes de contarla",  
"Recuerda que todo lo que necesitas para avanzar ya está dentro de ti",  
"La felicidad está en encontrar alegría en las pequeñas cosas",  
"Cada desafío te prepara para algo más grande, enfréntalo con valentía",  
"El esfuerzo que haces hoy será tu recompensa mañana",  
"Tu paz interior es tu mayor tesoro, protégela",  
"El éxito es la suma de pequeños esfuerzos repetidos día tras día",  
"Confía en tu intuición, ella siempre sabe el camino correcto",  
"El cambio empieza por dentro, trabaja en ti mismo primero",  
"La paciencia es la virtud que transforma el esfuerzo en éxito",  
"Recuerda que cada obstáculo es una oportunidad para mejorar",  
"La gratitud transforma las dificultades en bendiciones",  
"Hoy es un buen día para soltar lo que no puedes controlar",  
"La perseverancia siempre tiene su recompensa",  
"Las decisiones que tomas hoy moldean tu futuro",  
"Confía en el proceso y en el ritmo de la vida",  
"El aprendizaje constante es el secreto del crecimiento personal",  
"Rodéate de personas que te inspiren a ser tu mejor versión",  
"Cada momento tiene el potencial de ser transformador si lo permites",  
"El amor propio no es egoísmo, es una necesidad",  
"La felicidad no se encuentra en las cosas, sino en cómo las vives",  
"El cambio comienza cuando decides actuar con determinación",  
"El éxito no se mide en resultados, sino en el esfuerzo que pones",  
"La gratitud te conecta con la abundancia del universo",  
"Cada día es una nueva oportunidad para empezar de nuevo",
"El éxito comienza con la decisión de intentarlo",  
"La confianza en ti mismo es el mayor regalo que puedes darte",  
"Las pequeñas acciones de hoy construyen el futuro que deseas",  
"El camino hacia tus sueños siempre comienza con un paso",  
"El amor propio es el primer paso hacia una vida auténtica",  
"Cada obstáculo es una oportunidad para descubrir tu fuerza interior",  
"La gratitud es el camino más rápido hacia la felicidad",  
"Confía en que todo lo que ocurre tiene un propósito",  
"El presente es donde sucede la magia, no lo desperdicies",  
"Rodéate de lo que te inspire y deja ir lo que no te aporta",  
"La constancia es el secreto detrás de los grandes logros",  
"El cambio no es fácil, pero siempre vale la pena",  
"Tu historia importa, compártela con orgullo",  
"El crecimiento personal requiere tiempo, sé paciente contigo mismo",  
"El esfuerzo constante te lleva más lejos que la perfección",  
"El mejor regalo que puedes darte es creer en ti mismo",  
"Recuerda que eres capaz de superar cualquier desafío",  
"Cada día trae consigo una nueva oportunidad de aprender",  
"Tu mente es poderosa, enfócate en lo que deseas, no en lo que temes",  
"La paz interior es la base para tomar decisiones con claridad",  
"El éxito no llega de inmediato, pero siempre recompensa la perseverancia",  
"Confía en el proceso, incluso si el camino parece incierto",  
"Las mejores cosas de la vida toman tiempo, sé paciente",  
"La gratitud transforma cada día en un regalo",  
"El esfuerzo de hoy será la recompensa del mañana",  
"La confianza en ti mismo es el inicio de grandes logros",  
"Cada día es una nueva oportunidad para ser mejor que ayer",  
"Rodéate de personas que valoren y respeten tu esencia",  
"La felicidad está en las pequeñas cosas que haces con intención",  
"Cada desafío trae consigo una lección valiosa",  
"Tu actitud positiva es el motor de tu éxito",  
"El cambio comienza cuando decides tomar acción",  
"Confía en tu capacidad de crear la vida que deseas",  
"El amor propio es la clave para una vida equilibrada",  
"Recuerda que lo que piensas, creas",  
"Cada momento es una oportunidad para crecer y evolucionar",  
"La gratitud es la llave que abre las puertas de la abundancia",  
"El presente es el mejor momento para empezar",  
"La perseverancia transforma lo imposible en posible",  
"Confía en el camino, incluso si no puedes ver el destino",  
"Rodéate de energía positiva y deja ir lo que te pesa",  
"El éxito no es el final, es el resultado del esfuerzo constante",  
"Recuerda que eres suficiente tal como eres",  
"El amor propio no es egoísmo, es una necesidad para el bienestar",  
"Cada día es una oportunidad para empezar de nuevo con más fuerza",  
"Confía en el proceso y deja que la vida fluya",  
"La gratitud cambia tu enfoque y transforma tu realidad",  
"Rodéate de personas que te impulsen a crecer",  
"El cambio empieza contigo, toma las riendas de tu vida",  
"El esfuerzo constante es la base de los grandes logros",  
"Recuerda que cada paso cuenta, por pequeño que sea",  
"Tu historia tiene el poder de inspirar a otros",  
"La felicidad no está en el destino, está en el camino",  
"El aprendizaje constante es el secreto del crecimiento personal",  
"El éxito es el resultado de la confianza en ti mismo y el esfuerzo",  
"Confía en que lo mejor está por venir",  
"Cada desafío que enfrentas te hace más fuerte",  
"El cambio más pequeño puede generar grandes resultados",  
"Rodéate de lo que te haga sentir vivo y auténtico",  
"La gratitud abre el camino hacia una vida más plena",  
"El amor propio es la base para construir relaciones saludables",  
"Confía en que todo lo que ocurre tiene un propósito mayor",  
"El presente es donde tienes el poder de actuar",  
"La paciencia y la constancia son las claves del éxito",  
"Recuerda que lo que hoy parece difícil, mañana será una victoria",  
"Cada día es una nueva oportunidad para dar lo mejor de ti",  
"El esfuerzo que haces ahora será tu recompensa en el futuro",  
"Confía en tu intuición, siempre sabe el camino correcto",  
"El cambio requiere valentía, pero siempre trae crecimiento",  
"Rodéate de personas que celebren tu éxito y te impulsen a más",  
"La gratitud transforma los momentos ordinarios en extraordinarios",  
"Confía en tu capacidad de superar cualquier desafío",  
"El amor propio es el mejor regalo que puedes darte",  
"El éxito llega cuando decides no rendirte",  
"Recuerda que cada día es una página en blanco para escribir tu historia",  
"El esfuerzo constante siempre tiene su recompensa",
"Hoy es un buen día para creer en ti y en tus capacidades",  
"Agradece por lo que tienes y trabaja por lo que deseas",  
"Cada pequeño paso cuenta en el camino hacia tus sueños",  
"El presente es un regalo, vívelo con intención y amor",  
"La gratitud transforma lo que tenemos en suficiente",  
"Confía en el proceso, todo llega a su tiempo",  
"Hoy es la oportunidad de empezar de nuevo con más fuerza",  
"Las cosas pequeñas hechas con amor generan grandes cambios",  
"No compares tu camino con el de otros, tu historia es única",  
"Haz de cada día una oportunidad para aprender y crecer",  
"Tu actitud puede convertir cualquier día en uno especial",  
"Encuentra belleza en las cosas simples y deja que te inspiren",  
"Cada desafío es una lección disfrazada, acéptala con valentía",  
"El esfuerzo constante es la clave para alcanzar tus metas",  
"El éxito empieza en el momento en que decides no rendirte",  
"Rodéate de personas que te impulsen a ser tu mejor versión",  
"Un corazón agradecido siempre encuentra razones para sonreír",  
"El cambio comienza cuando decides dar el primer paso",  
"Tu energía fluye hacia donde enfocas tu atención, elige bien",  
"Cada amanecer es una nueva oportunidad para comenzar de nuevo",  
"Ser amable contigo mismo es tan importante como serlo con los demás",  
"Confía en tu intuición, siempre sabe hacia dónde guiarte",  
"Haz lo mejor que puedas con lo que tienes en este momento",  
"El éxito no es un destino, es un viaje que construyes día a día",  
"A veces, lo que más temes es justo lo que necesitas enfrentar",  
"La vida es mejor cuando te enfocas en lo positivo",  
"Sé la luz que ilumine tu camino y el de quienes te rodean",  
"Recuerda que eres capaz de superar cualquier obstáculo",  
"Cada día tienes la oportunidad de reescribir tu historia",  
"Tu potencial no tiene límites, atrévete a explorarlo",  
"La paz interior es tu verdadero poder, cuídala",  
"La acción más pequeña es mejor que la intención más grande",  
"El cambio que deseas ver en el mundo comienza contigo",  
"El tiempo que dedicas a crecer nunca es tiempo perdido",  
"Elimina las dudas y da espacio a la confianza en ti mismo",  
"El éxito empieza con una mentalidad positiva y abierta",  
"La paciencia y la constancia siempre rinden frutos",  
"Cada momento tiene el potencial de ser especial si tú lo decides",  
"El aprendizaje es un regalo que siempre puedes darte a ti mismo",  
"A veces, la pausa que temes es lo que necesitas para avanzar",  
"No necesitas tener todo resuelto, solo el coraje de intentarlo",  
"La felicidad no es el destino, es el camino que recorres",  
"Las oportunidades llegan a quienes están preparados para tomarlas",  
"La confianza en ti mismo es el primer paso hacia el éxito",  
"Abraza los retos, son escalones hacia tus sueños",  
"El presente es el único momento que realmente tienes, hazlo valer",  
"Nunca subestimes el poder de tus palabras y tus acciones",  
"La gratitud abre la puerta a más bendiciones",  
"No importa cuántas veces caigas, lo importante es levantarte",  
"Tus pensamientos moldean tu realidad, elige con sabiduría",  
"Haz más de lo que te hace sentir vivo y auténtico",  
"El poder de tus sueños es mayor que tus miedos",  
"La clave para avanzar es actuar con valentía, incluso con dudas",  
"Hoy es un buen día para soltar lo que no puedes controlar",  
"Haz espacio en tu vida para lo que realmente importa",  
"La calma y el enfoque son tus mejores aliados en días difíciles",  
"Tu esfuerzo de hoy es la recompensa de mañana",  
"Eres capaz de lograr cosas increíbles cuando confías en ti",  
"La pasión y el compromiso siempre encuentran el camino",  
"Cree en la magia de los comienzos, son oportunidades disfrazadas",  
"Las pequeñas victorias diarias suman grandes logros",  
"Un corazón agradecido siempre atrae abundancia",  
"La confianza en el proceso es clave para alcanzar tus metas",  
"La mejor inversión que puedes hacer es en ti mismo",  
"El tiempo que dedicas a tus sueños nunca será tiempo perdido",  
"La perseverancia convierte lo imposible en posible",  
"Recuerda que cada día es un regalo para empezar de nuevo",  
"Los límites solo existen en tu mente, expándelos",  
"Las mejores ideas nacen en momentos de calma y reflexión",  
"Sé paciente contigo mismo, el crecimiento lleva tiempo",  
"Agradece por cada obstáculo, son parte de tu aprendizaje",  
"El coraje no es la ausencia de miedo, es actuar a pesar de él",  
"Haz de la autocompasión tu herramienta para avanzar",  
"La vida siempre tiene algo nuevo que enseñarte, escúchala",  
"Tu historia tiene el poder de inspirar a otros, cuéntala",  
"La disciplina es el puente entre tus metas y tus logros",  
"Lo que hoy parece difícil, mañana será parte de tu fortaleza",  
"La inspiración está en todas partes, solo necesitas verla",  
"El éxito es el resultado de la constancia y el trabajo inteligente",  
"El cambio siempre empieza con una decisión valiente",  
"Tu paz interior vale más que cualquier cosa, protégela",  
"El amor propio es la base de una vida plena y auténtica",  
"Recuerda que eres suficiente, tal como eres en este momento",  
"La bondad hacia los demás empieza con la bondad hacia ti mismo",  
"Tu energía es tu recurso más valioso, úsala sabiamente",
"Cada día es una nueva oportunidad para empezar de nuevo",  
"Confía en el camino, incluso cuando no veas el final",  
"Lo que sueñas está a tu alcance, solo necesitas actuar",  
"Todo lo que necesitas ya está dentro de ti",  
"La paz comienza en tu interior, cultívala",  
"Todo cambio comienza con una sola decisión",  
"Cada momento es una nueva chance para ser mejor",  
"Lo que siembras hoy, cosecharás mañana",  
"La vida siempre te da lo que necesitas, incluso si no lo entiendes de inmediato",  
"Todo lo que haces con amor tiene un impacto positivo",  
"La felicidad está en el camino, no solo en el destino",  
"La abundancia comienza con la gratitud",  
"Hoy es un día perfecto para comenzar a cuidar de ti",  
"Cada desafío es una oportunidad disfrazada",  
"La clave para la paz es la aceptación",  
"Cada día te acercas más a tus metas",  
"No te rindas, lo mejor aún está por venir",  
"El amor propio es el primer paso hacia el amor incondicional",  
"Tu actitud determina el rumbo de tu vida",  
"Lo que piensas, lo creas",  
"La grandeza está en los pequeños detalles",  
"En cada error hay una lección valiosa",  
"Tu vida refleja tus pensamientos, elige bien",  
"El universo está conspirando a tu favor",  
"Tu potencial es ilimitado, cree en él",  
"El futuro pertenece a quienes creen en el poder de sus sueños",  
"La serenidad se encuentra en la aceptación",  
"El primer paso hacia el cambio es decidirlo",  
"La vida se vuelve más fácil cuando te sueltas y confías",  
"Todo en la vida llega en el momento perfecto",  
"Las oportunidades están en todas partes, abre los ojos",  
"El esfuerzo diario es la semilla del éxito futuro",  
"Cada paso hacia adelante te acerca más a tu objetivo",  
"La gratitud transforma el caos en claridad",  
"La energía positiva atrae más cosas positivas",  
"La mente es más poderosa de lo que crees",  
"Cada día trae consigo una nueva oportunidad para crecer",  
"El primer paso es siempre el más difícil, pero el más valioso",  
"Hoy es un buen día para hacer algo por ti",  
"Confía en ti mismo, no necesitas la aprobación de los demás",  
"Lo que sucede en tu vida es solo un reflejo de lo que tienes dentro",  
"Las decisiones que tomas hoy definen tu mañana",  
"Cada día es una página en tu historia, haz que cuente",  
"El momento presente es todo lo que tienes, vívelo plenamente",  
"La gratitud es la clave para atraer abundancia",  
"No hay sueños imposibles, solo metas aún no alcanzadas",  
"El éxito es la suma de pequeños esfuerzos repetidos cada día",  
"Tu actitud hoy determina tu éxito mañana",  
"La vida comienza donde termina la zona de confort",  
"Cada experiencia te enseña algo nuevo",  
"El verdadero éxito radica en la paz interior",  
"Los cambios más grandes vienen de los pequeños pasos",  
"Cada vez que te caes, te estás levantando más fuerte",  
"La belleza está en los ojos del que mira, elige ver lo bueno",  
"El momento perfecto es el ahora",  
"Todo lo que necesitas está en tu interior, confía en ti",  
"La disciplina es la clave que abre todas las puertas",  
"Las dificultades son solo escalones hacia el éxito",  
"El camino hacia el éxito está pavimentado con esfuerzo",  
"El miedo es solo una emoción, no una barrera",  
"Cada día es una oportunidad para ser tu mejor versión",  
"La vida es un reflejo de tu mentalidad",  
"Las bendiciones vienen cuando eres agradecido por lo que ya tienes",  
"Hoy es un buen día para empezar a creer en lo imposible",  
"Tu vida es tan grandiosa como decidas verla",  
"La calma es tu mayor aliada en tiempos de caos",  
"El amor propio es la base de una vida llena de paz",  
"Cada pensamiento positivo te acerca a tu objetivo",  
"El éxito se encuentra en la perseverancia",  
"Cada día es una nueva oportunidad para hacer una diferencia",  
"La gratitud transforma lo ordinario en extraordinario",  
"La vida es un regalo, disfrútala sin reservas",  
"Todo lo que quieres está al otro lado del miedo",  
"La felicidad se encuentra dentro de ti, no en las circunstancias",  
"Lo que haces hoy crea la realidad de mañana",  
"Hoy es el día perfecto para empezar a construir tu futuro",  
"Tu potencial es infinito, no pongas límites a tus sueños",  
"Cada día trae consigo una nueva oportunidad para brillar",  
"Todo lo que haces con amor tiene un impacto positivo en el mundo",  
"Tu mente es la herramienta más poderosa que tienes, úsala sabiamente",  
"Cada reto es una oportunidad para aprender y crecer",  
"Confía en el proceso, todo tiene un propósito",  
"La vida te da lo que necesitas, no lo que deseas",  
"El éxito no es cuestión de suerte, sino de persistencia",  
"Hoy es el primer día del resto de tu vida",  
"Tu felicidad comienza con lo que eliges pensar",  
"Los sueños no tienen fecha de vencimiento, sigue persiguiéndolos",  
"Recuerda siempre que eres más fuerte de lo que piensas",  
"Las oportunidades no llegan, se crean",  
"La perseverancia te llevará más lejos que el talento",  
"Cada pensamiento positivo cambia tu realidad",  
"Tu vida está llena de posibilidades, elige las que más te emocionen",  
"Lo más importante es comenzar, el resto lo aprenderás en el camino",  
"El éxito es un viaje, no un destino",  
"Todo lo que siembras en tu vida, lo cosecharás",  
"La gratitud cambia tu perspectiva y te abre puertas",  
"El amor propio es la base para una vida de éxito",  
"Hoy es el mejor día para empezar a ser la mejor versión de ti",  
"Cada desafío es solo una oportunidad para crecer",  
"Todo lo que hagas con pasión te llevará lejos",  
"La vida es una serie de momentos, disfrútalos uno a uno",  
"Todo lo que necesitas está en tu interior, solo tienes que creer",  
"La paciencia es la clave que desbloquea todo lo bueno",  
"Hoy es un buen día para empezar de nuevo",  
"Confía en tu intuición, siempre te guía hacia lo correcto",  
"El éxito no es cuestión de suerte, es de constancia",  
"Cada paso cuenta, sigue avanzando",  
"El cambio comienza cuando decides hacerlo",  
"Los mejores momentos de la vida ocurren fuera de la zona de confort",  
"Tu vida refleja lo que crees, cree en grande",  
"La paz comienza con un pensamiento tranquilo",  
"Cada momento es una nueva oportunidad para ser feliz",  
"Tu mentalidad puede cambiar tu realidad",  
"Lo que piensas, lo que sientes, lo que haces, crea tu vida",  
"Hoy es el día perfecto para empezar a cambiar",  
"Las oportunidades siempre están a tu alrededor, solo tienes que verlas",  
"Todo lo que necesitas es la voluntad de intentarlo",  
"Hoy es un buen día para avanzar hacia tus sueños",  
"Todo lo que haces hoy te acerca a tus metas",  
"Tu historia está siendo escrita, hazla memorable",  
"La gratitud convierte lo que tenemos en suficiente",  
"Hoy es el primer paso hacia el futuro que deseas",  
"El poder de crear está dentro de ti, empieza hoy",  
"Cada vez que te caes, te haces más fuerte",  
"El amor propio es la clave para una vida plena",  
"Cada día trae consigo un nuevo comienzo",  
"La paz está en tu mente, elige mantenerla",  
"Todo lo que sueñas está esperando que tomes acción",  
"La verdadera felicidad radica en disfrutar el presente",  
"La vida es el reflejo de tus pensamientos",  
"Hoy es el mejor día para ser tú mismo",  
"El éxito se logra con consistencia y esfuerzo diario",  
"Tu vida cambiará cuando cambien tus pensamientos",  
"Cada pequeño paso es un avance hacia tus sueños",  
"El universo siempre está alineado a tu favor",  
"La gratitud transforma cada momento en una bendición",  
"Hoy es un buen día para cambiar tu mentalidad",  
"La mejor manera de predecir el futuro es crearlo",  
"Cada nuevo día es una nueva oportunidad para ser feliz",  
"La felicidad se crea dentro de ti, no en las circunstancias",  
"Hoy es el mejor momento para empezar a ser mejor",  
"El cambio comienza cuando tú decides hacerlo",  
"Cada desafío trae consigo una gran oportunidad",  
"Tu historia está en tus manos, hazla increíble",  
"La vida siempre te da lo que necesitas, confía",  
"Hoy es un buen día para enfocarte en tus metas",  
"Tu actitud determina todo lo que te sucede",  
"Todo lo que piensas tiene el poder de hacerse realidad",  
"La paz es la clave para lograr todo lo que te propones",  
"Hoy es un buen día para ser feliz",  
"Cada día es una nueva oportunidad para reinventarte",  
"Lo que haces hoy será tu futuro",  
"Confía en el proceso y todo llegará en el momento adecuado",  
"Las oportunidades están a tu alrededor, solo debes verlas",  
"Cada pensamiento positivo te acerca más a tus metas",
"Cada desafío es una oportunidad para evolucionar",  
"Hoy es el primer día del resto de tu vida, hazlo contar",  
"Todo lo que haces con amor tiene un impacto positivo en el mundo",  
"Hoy es un buen día para empezar a creer en ti mismo",  
"El éxito comienza en el momento en que decides no rendirte",  
"Cada pequeña victoria te acerca al éxito",  
"El éxito está en tu perseverancia y paciencia",  
"Hoy es un buen día para dejar ir lo que no puedes controlar",  
"Cada paso que das es un paso hacia tus sueños",  
"El futuro pertenece a aquellos que creen en sus sueños",  
"Cada error es una lección que te acerca a tu meta",  
"Hoy es un buen día para dar lo mejor de ti",  
"El éxito se construye con pequeños esfuerzos constantes",  
"Hoy es un buen día para ser el mejor version de ti mismo",  
"Lo que sueñas está más cerca de lo que piensas",  
"Todo lo que necesitas ya está en ti, solo confía",  
"La felicidad está dentro de ti, solo tienes que encontrarla",  
"Cada desafío es una oportunidad para crecer",  
"Hoy es el primer paso hacia tu futuro brillante",  
"El éxito es una consecuencia del esfuerzo constante",  
"Tu vida es el reflejo de lo que piensas, elige bien",  
"La perseverancia te llevará a donde quieras llegar",  
"Cada día es una nueva página en tu historia",  
"Hoy es el día perfecto para comenzar a ser tu mejor versión",  
"Confía en el proceso, todo llega en su momento",  
"El éxito es un camino, no un destino",  
"Hoy es el mejor día para empezar a cambiar",  
"Cada momento es una nueva oportunidad para empezar",  
"Lo mejor de ti está por venir, sigue adelante",  
"Hoy es un buen día para soltar el miedo y seguir tus sueños",  
"Lo que haces hoy impactará tu futuro",  
"Hoy es el primer paso hacia una vida increíble",  
"Confía en el proceso, todo sucede por una razón",  
"Hoy es un buen día para empezar a creer en lo imposible",  
"Todo lo que haces con pasión y dedicación te llevará lejos",  
"Hoy es el día perfecto para tomar decisiones valientes",  
"Cada paso que tomas te acerca más a lo que deseas",  
"El éxito comienza cuando decides creer en ti",  
"Hoy es un buen día para avanzar hacia lo que deseas",  
"Todo lo que piensas se convierte en tu realidad",  
"Hoy es un buen día para empezar a ser tu mejor versión",  
"Cada reto trae consigo una oportunidad para crecer",  
"El universo conspira a tu favor, confía",  
"Hoy es un buen día para dar un paso hacia tu mejor versión",  
"El éxito llega con paciencia y persistencia",  
"Hoy es el mejor día para tomar el control de tu vida",  
"Cada error es solo un paso más hacia el éxito",  
"Hoy es un buen día para empezar a creer en ti mismo",  
"Todo lo que quieres está al alcance de tu mano",  
"Hoy es el día para decidir quién quieres ser",  
"Cada día es una oportunidad para empezar de nuevo",  
"El éxito se construye con perseverancia",  
"Hoy es un buen día para empezar a trabajar en tus sueños",  
"El futuro pertenece a los que creen en su poder",  
"Hoy es el mejor día para empezar a cambiar tu vida",  
"Cada paso que das te acerca a tus metas",  
"El éxito está a solo un paso de salir de tu zona de confort",  
"Hoy es el primer día de tu nuevo comienzo",  
"El éxito empieza cuando decides creer en ti",  
"Hoy es el día perfecto para empezar a crear la vida que deseas",  
"Cada desafío es una oportunidad para crecer",  
"Hoy es el día para empezar a invertir en tu felicidad",  
"Todo lo que necesitas está dentro de ti",  
"Hoy es un buen día para avanzar hacia tus sueños",  
"Confía en ti mismo y todo se alineará a tu favor",  
"Hoy es el día perfecto para comenzar un nuevo capítulo",  
"Todo lo que haces con amor se multiplicará",  
"Hoy es el día para dejar ir lo que no te sirve",  
"Cada paso te lleva más cerca de tus sueños",  
"Hoy es el día para creer en lo que eres capaz de lograr",  
"El éxito está en tu perseverancia",  
"Hoy es un buen día para crear nuevas oportunidades",  
"Todo lo que necesitas para ser feliz está dentro de ti",  
"Hoy es un buen día para dejar de lado las dudas",  
"Cada día es una nueva oportunidad para ser feliz",  
"El universo siempre tiene un plan perfecto para ti",  
"Hoy es el día perfecto para empezar a ser tú mismo",  
"Todo lo que sueñas está al alcance de tu mano",  
"Hoy es el día perfecto para creer en lo imposible",  
"Cada pensamiento positivo te acerca más a tu meta",  
"Hoy es el mejor día para empezar a cambiar tu vida",  
"Todo lo que haces con pasión te llevará lejos",  
"Hoy es un buen día para empezar a creer en lo que eres capaz",  
"El futuro está lleno de oportunidades, solo tienes que tomarlas",  
"Hoy es el día perfecto para empezar a confiar en ti mismo",  
"Cada paso cuenta, sigue avanzando",  
"Hoy es el mejor día para empezar a transformar tu vida",  
"Todo lo que necesitas para ser feliz está en tu interior",  
"Hoy es un buen día para abrazar tus sueños",  
"Todo lo que deseas está más cerca de lo que piensas",  
"Hoy es el mejor día para empezar a ser tu mejor versión",  
"Cada día es una oportunidad para aprender algo nuevo",  
"Hoy es un buen día para seguir tus sueños",  
"El universo siempre tiene una razón para cada cosa",  
"Hoy es el día perfecto para empezar a crear la vida que deseas",  
"Cada pensamiento positivo te acerca a tus metas",  
"Hoy es el día para confiar en tu camino",  
"Todo lo que haces con amor tiene un impacto positivo",  
"Hoy es un buen día para empezar a creer en ti",  
"Cada paso te lleva más cerca de tus sueños",  
"Hoy es el mejor día para empezar a trabajar por tu futuro",  
"Todo lo que necesitas ya está dentro de ti",  
"Hoy es un buen día para avanzar hacia tus metas",  
"El éxito comienza con una mentalidad positiva",  
"Hoy es un buen día para empezar a dejar ir el miedo",  
"Cada paso que tomas te acerca más a lo que deseas",  
"Hoy es el primer paso hacia el futuro que deseas",  
"Todo lo que sueñas está esperando que tomes acción",  
"Hoy es el día para crear nuevas oportunidades",  
"Cada pensamiento positivo te acerca más a tus sueños",  
"Hoy es un buen día para seguir adelante",  
"Todo lo que haces hoy tendrá un impacto en tu mañana",  
"Hoy es el mejor día para empezar a cambiar",  
"Cada paso te acerca más a tus metas",  
"Hoy es el día perfecto para comenzar a creer en ti",  
"Todo lo que sueñas está esperando que tomes acción",  
"Hoy es el día para empezar a crear la vida que deseas"
]
export default arregloFrases;